현재 epoch-19의 test-데이터 셋에서 평균 Loss : 0.045, 평균 Accuracy : 0.970, 평균 f1 : 0.915
학습 종료!
최고 accuracy : 0.973809540271759, 최고 낮은 loss : 0.044294317047636485, 최고 높은 f1 : 0.930852550753922

wandb: Currently logged in as: jaehyung25 (use `wandb login --relogin` to force relogin)
start making image path
finish making labeled data
load dataset
load finished

CondaEnvException: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.

wandb: Tracking run with wandb version 0.12.1
wandb: Syncing run good-snowball-5
wandb:  View project at https://wandb.ai/jaehyung25/mask_classification
wandb:  View run at https://wandb.ai/jaehyung25/mask_classification/runs/1gchwgam
wandb: Run data is saved locally in /opt/ml/code/image-classification-level1-18/code/wandb/run-20210831_064931-1gchwgam
wandb: Run `wandb offline` to turn off syncing.
  0% 0/473 [00:00<?, ?it/s]
cuda:0 is using!
                           Traceback (most recent call last):
  File "main.py", line 27, in <module>
    traine.start(train_dataset,val_dataset)
  File "/opt/ml/code/image-classification-level1-18/code/traine.py", line 76, in start
    for ind, (images, labels) in enumerate(tqdm.tqdm(dataloaders['train'],leave=False)):
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 272, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/opt/ml/code/image-classification-level1-18/code/dataset.py", line 65, in __getitem__
    image_transform = self.transform(image=np.array(image))['image']
  File "/opt/conda/lib/python3.8/site-packages/albumentations/core/composition.py", line 191, in __call__
    data = t(force_apply=force_apply, **data)
  File "/opt/conda/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 90, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 103, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/opt/conda/lib/python3.8/site-packages/albumentations/augmentations/transforms.py", line 647, in apply
    return F.normalize(image, self.mean, self.std, self.max_pixel_value)
  File "/opt/conda/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 141, in normalize
    img -= mean
ValueError: operands could not be broadcast together with shapes (224,244,4) (3,) (224,244,4) 

wandb: Waiting for W&B process to finish, PID 18304
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: / 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: / 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: / 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb:                                                                                
wandb: Find user logs for this run at: /opt/ml/code/image-classification-level1-18/code/wandb/run-20210831_064931-1gchwgam/logs/debug.log
wandb: Find internal logs for this run at: /opt/ml/code/image-classification-level1-18/code/wandb/run-20210831_064931-1gchwgam/logs/debug-internal.log
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: 
wandb: Synced good-snowball-5: https://wandb.ai/jaehyung25/mask_classification/runs/1gchwgam

